name: Kotlin Check Everything

on:
  release:
    types: [created]

jobs:
  fatJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Shadow Jar
        run: ./gradlew shadowJar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/JexCompiler-1.0-SNAPSHOT-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
