name: Kotlin Check Everything

on:
  push: null
  release:
    types: [created]

jobs:
  fatJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Shadow Jar
        run: ./gradlew shadowJar
      - name: Upload Fat Jar
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JexCompiler
          path: build/libs/JexCompiler-1.0-SNAPSHOT-all.jar
